tap "apparition47/tap"
tap "erictli/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "theseal/blank-screensaver"
brew "bat"
brew "coreutils"
brew "dotnet"
brew "git"
brew "lsd"
brew "mas"
brew "mole"
brew "pyenv"
brew "uv"
brew "xcodes"
brew "zplug"
cask "bbedit"
cask "chatgpt"
cask "codex"
cask "codex-app"
cask "font-sauce-code-pro-nerd-font"
cask "ghostty"
cask "keepingyouawake"
cask "logi-options+"
cask "mullvad-vpn"
cask "openemu"
cask "rectangle"
cask "sf-symbols"
cask "transmission"
cask "visual-studio-code"
cask "zoom"
mas "DaisyDisk", id: 411643860
mas "iFlicks 3", id: 1274494218
mas "iMovie", id: 408981434
mas "Ivory", id: 6444602274
mas "Noir", id: 1592917505
mas "Wipr", id: 1662217862
vscode "ardonplay.vscode-jetbrains-full-icon-theme"
vscode "charliermarsh.ruff"
vscode "fogio.jetbrains-color-theme"
vscode "guyskk.language-cython"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-ssh"
vscode "openai.chatgpt"
vscode "tamasfe.even-better-toml"
